sbatch_normal_mem: "100G"
sbatch_high_mem: "250G"
virome_min_len: 2000
minimum_number_of_virome_input_contigs: 1
long_contig_cutoff: 150000
threads: 2
dvf_path: "/home/dlueckin/bin/DeepVirFinder/dvf.py"
viromeQC_path: "/home/dlueckin/bin/viromeqc"
platon_db: "/home/dlueckin/dbs/platon_db/db/"
vs2_db: "/home/dlueckin/dbs/vs2/db/"
checkv_db: "/home/dlueckin/dbs/checkv-db-v1.0"
kaiju_fmi: "/bioinf/home/dlueckin/dbs/kaiju_db_nr/kaiju_db_nr.fmi"
kaiju_nodes: "/bioinf/home/dlueckin/dbs/kaiju_db_nr/nodes.dmp"
kaiju_names: "/bioinf/home/dlueckin/dbs/kaiju_db_nr/names.dmp"
mv_producer_list: "data/mv_producer/list_of_mv_producer.list"
samples:
    # - 100_DCM
    # - 100_SRF
    # - 102_DCM
    # - 102_MES
    # - 102_SRF
    # - 109_DCM
    # - 109_SRF
    # - 111_DCM
    # - 111_MES # missing reads -> found reads by selecting the second read file in the table
    # - 111_SRF
    # - 11_SRF
    # - 122_DCM
    # - 122_MES
    # - 122_SRF
    # - 123_MIX
    # - 123_SRF # missing reads -> found reads by selecting the second read file in the table
    # - mv1 -> done
    # - mv11 -> done
    # - mv13 -> done
    # - mv14 -> done
    # - mv15 -> done
    # - mv16 -> done
    # - mv2 -> done
    # - mv3 -> done
    # - mv4 -> done
    # - mv5 -> done
    # - mv6 -> done
    # - mv8 -> done
    # - mv9 -> done
    # - SRR12115929 -> done
    # - SRR12115932 -> done
    # - SRR12115934 -> done
    # - SRR12115961 -> done
    # - SRR12115962 -> done
    # - SRR12115967 -> done
    # - SRR12115970 -> done
    # - virome -> done
    - SRR12115930
    - SRR12115931
    - SRR12115933
    - SRR12115938
    - SRR12115949
    - SRR12115951
    - SRR12115963
    - SRR12115964
    - SRR12115965
    - SRR12115966
    - SRR12115968
    - SRR12115969

