sbatch_normal_mem: "100G"
sbatch_high_mem: "250G"
virome_min_len: 2000
minimum_number_of_virome_input_contigs: 1
long_contig_cutoff: 150000
threads: 2
dvf_path: "/home/dlueckin/bin/DeepVirFinder/dvf.py"
viromeQC_path: "/home/dlueckin/bin/viromeqc"
platon_db: "/home/dlueckin/dbs/platon_db/db/"
vs2_db: "/home/dlueckin/dbs/vs2/db/"
checkv_db: "/home/dlueckin/dbs/checkv-db-v1.0"
kaiju_fmi: "/bioinf/home/dlueckin/dbs/kaiju_db_nr/kaiju_db_nr.fmi"
kaiju_nodes: "/bioinf/home/dlueckin/dbs/kaiju_db_nr/nodes.dmp"
kaiju_names: "/bioinf/home/dlueckin/dbs/kaiju_db_nr/names.dmp"
mv_producer_list: "data/mv_producer/list_of_mv_producer.list"
samples:
    # - 111_MES
    # - 137_MES
    # - 138_MES
    # - 155_MES # later
    - 168_DCM
    - 168_SRF
    # - 173_DCM # later
    # - 175_SRF
    # - 175_ZZZ
    # - 178_SRF
    # - 18_DCM
    # - 18_SRF
    # - 180_DCM
    # - 188_DCM
    # - 201_MES
    # - 201_SRF
    # - 205_MES
    # - 206_MES
    # - 206_SRF
    # - 208_SRF
    # - 209_MES
    # - 209_SRF
    # - 34_DCM
    # - 34_SRF
    # - 36_DCM
    # - 36_SRF
    # - 37_MES1
    # - 38_DCM
    # - 38_MES
    # - 38_SRF
    # - 39_DCM
    # - 39_MES
    # - 39_SRF
    # - 41_DCM
    # - 41_SRF
    # - 42_DCM
    # - 42_SRF
    # - 45_SRF
    # - 46_SRF
    # - 48_SRF
    # - 52_DCM
    # - 52_SRF
    # - 56_MES
    # - 56_SRF
    # - 58_DCM
    # - 62_SRF
    # - 65_DCM
    # - 65_SRF
    # - 66_DCM
    # - 66_SRF
    # - 67_SRF
    # - 68_DCM
    # - 68_MES
    # - 68_SRF # some error
    # - 70_MES # some error
    # - 70_SRF
    # - 72_DCM
    # - 72_MES
    # # - 72_SRF
    # - 76_DCM
    # # - 76_MES
    # # - 76_SRF
    # # - 78_DCM
    # - 78_MES
    # - 78_SRF
    # - 85_DCM -> need solution for dvf
    # - 85_MES
    # - 85_SRF
    # - 82_DCM
    # - 82_SRF -> done
    # - 84_SRF -> done
    # - 122_DCM -> done and moved to three_stations
    # - 122_MES -> done and moved to three_stations
    # - 122_SRF -> done and moved to three_stations
    # - 158_DCM -> done and moved to three_stations
    # - 158_MES -> done and moved to three_stations
    # - 158_SRF -> done and moved to three_stations
    # - 64_DCM -> done and moved to three_stations
    # - 64_MES # -> this has been resequenced: ERR2752155
    # - 64_SRF # -> done and moved to three_stations
    # # - 193_SRF
    # - 194_DCM
    # # - 194_SRF
    # # - 196_SRF
    # # - 201_DCM
    # - 201_MES
    # - 201_SRF
    # - 205_MES 
    # # - 205_SRF
    # - 206_MES
    # - 206_SRF
    # - 208_SRF
    # - 209_MES
    # - 209_SRF
    # - 210_MES
    # - 210_SRF
    # - 22_SRF
    # - 23_DCM
    # - 25_DCM
    # - 25_SRF
    # - 30_DCM
    # - 31_SRF
    # - 32_DCM
    # - 32_SRF
    # - 33_SRF
    # - 178_SRF # problem!
    # - 180_DCM # problem!
    # - 188_DCM # problem!
    # - 138_MES # problem!
    # - 158_DCM # problem!
    # - 158_MES # problem!
    # - 168_SRF # problem!
    # - 168_DCM # problem!
    # - 175_SRF # problem!
    # - 173_DCM # problem!
    # - 137_MES # problem!
    # - 111_MES # problem!
    # - 122_MES # problem!
    # - 155_MES # problem!
    # - 175_ZZZ # problem!
    # - 4976_AA --> done and moved!
    # - 4976_AB --> done and moved!
    # - 4976_AD --> done and moved!
    # - 4976_AE --> done and moved!
    # - 100_DCM --> done and moved!
    # - 100_SRF --> done and moved!
    # - 102_DCM --> done and moved!
    # - 102_MES --> done and moved!
    # - 102_SRF --> done and moved!
    # - 109_DCM --> done and moved!
    # - 109_SRF --> done and moved!
    # - 111_DCM --> done and moved!
    # - 111_SRF --> done and moved!
    # - 11_SRF --> done and moved!
    # - 122_DCM --> done and moved!
    # - 122_SRF --> done and moved!
    # - 123_MIX --> done and moved!
    # - 123_SRF # missing reads -> found reads by selecting the second read file in the table
    # - 124_MIX --> done and moved!
    # - 124_SRF --> done and moved!
    # - 125_MIX --> done and moved!
    # - 125_SRF --> done and moved!
    # - 137_DCM --> done and moved!
    # - 137_SRF --> done and moved!
    # - 138_DCM --> done and moved!
    # - 138_SRF --> done and moved!
    # - 155_DCM --> done and moved!
    # - 155_SRF --> done and moved!
    # - 158_SRF --> done and moved!
    # - 163_MES --> done and moved!
    # - 173_SRF --> done and moved!
    # - 163_SRF --> done and moved!
    # - 168_MIX --> done and moved!
    # - 175_MIX --> done and moved!
    # - 180_SRF --> done and moved
    # - 188_SRF --> done and moved
    # - 189_DCM --> done and moved
    # - 189_MES --> done and moved
    # - 18_DCM --> done and moved
    # - 18_SRF --> done and moved
    # - 191_SRF --> done and moved
    # - mv1 --> done and moved!
    # - mv11 --> done and moved!
    # - mv13 --> done and moved!
    # - mv14 --> done and moved!
    # - mv15 --> done and moved!
    # - mv16 --> done and moved!
    # - mv2 --> done and moved!
    # - mv3 --> done and moved!
    # - mv4 --> done and moved!
    # - mv5 --> done and moved!
    # - mv6 --> done and moved!
    # - mv8 --> done and moved!
    # - mv9 --> done and moved!
    # - SRR12115929 --> done and moved!
    # - SRR12115932 --> done and moved!
    # - SRR12115934 --> done and moved!
    # - SRR12115961 --> done and moved!
    # - SRR12115962 --> done and moved!
    # - SRR12115967 --> done and moved!
    # - SRR12115970 --> done and moved!
    # - virome --> done and moved!
    # - SRR12115930 --> done and moved!
    # - SRR12115931 # there is a weird error with this one. Doesnt matter
    # - SRR12115933 --> done and moved!
    # - SRR12115938 --> done and moved!
    # - SRR12115949 --> done and moved!
    # - SRR12115951 --> done and moved!
    # - SRR12115963 --> done and moved!
    # - SRR12115964 --> done and moved!
    # - SRR12115965 --> done and moved!
    # - SRR12115966 --> done and moved!
    # - SRR12115968 --> done and moved!
    # - SRR12115969 --> done and moved!
    # - med4 --> done and moved!
    # - SRR1015709 --> done and moved!
    # - SRR1015707 --> done and moved!
    # - DRR173063 --> done and moved!
    # - DRR173064 --> done and moved!
    # - DRR173065 --> done and moved!
    # - DRR173066 --> done and moved!
    # - DRR173067 --> done and moved!
    # - DRR173069 --> done and moved!
    # - DRR173070 --> done and moved!
    # - DRR173071 --> done and moved!
    # - DRR173072 --> done and moved!
    # - DRR173073 --> done and moved!
    # - DRR173074 --> done and moved!
    # - DRR173075 --> done and moved!
    # - DRR173076 --> done and moved!
    # - DRR173077 --> done and moved!
    # - DRR173078 --> done and moved!
    # - DRR173079 --> done and moved!
    # - DRR173080 --> done and moved!
    # - DRR173081 --> done and moved!
    # - DRR173082 --> done and moved!
    # - DRR173083 --> done and moved!
    # - DRR173084 --> done and moved!
    # - DRR173085 --> done and moved!
    # - DRR173086 --> done and moved!
    # - DRR173087 --> done and moved!
    # - DRR173089 --> done and moved!
    # - DRR173090 --> done and moved!
    # - DRR173091 --> done and moved!
    # - DRR173093 --> done and moved!
    # - DRR173094 --> done and moved!

